plugins:
  - jekyll-remote-theme

remote_theme: fongandrew/hydeout

# Github Pages default (changeable)
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
# theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# Setup
title: Lingtorp
tagline: ''
description: 'Computer graphics and game engine tech.'